version: '3.8'

services:
  planefence-notifier:
  #
  # Add the services that need to be invoked comma separated to the NOTIFIERS environment variable.
  # If any of the notifier needs to pass in special credentials or parameters, these can be passed in
  # as environment variables. Please observe the following syntax:
  # - NOTIFY_xxxxx_VARIABLE=yyyyy where xxxxx is the notifier name in CAPITALS
  # - for example, NOTIFY_DISCORD_PAWEBHOOK=http://webhook
  # CLEANUPINTERVAL (units=minutes) optional -- if omitted, it defaults to 60 (minutes)
    image: kx1t/adsb-notifier
    tty: true
    container_name: adsb-notifier
    hostname: adsb-notifier
    restart: always
    environment:
      - CLEANUPINTERVAL=60
      - VERBOSELOG=true
      - VERBOSE=true
      - NOTIFIERS=twitter,discord,mqtt,ifttt
      - TWITTER_CONSKEY=${TWITTER_CONSKEY}
      - TWITTER_CONSSECRET=${TWITTER_CONSSECRET}
      - TWITTER_ACCTOKEN=${TWITTER_ACCTOKEN}
      - TWITTER_ACCSECRET=${TWITTER_ACCSECRET}
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 9999:80
