#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/php-fpm"

echo "[$APPNAME][$(date)] Started as an s6 service"

# create run directory. This is where the locations.conf file will be located.

php-fpm -g /run/php-fpm.pid -D
echo "[$APPNAME][$(date)] Up and running"
exec wait $(cat /tmp/php-fpm.pid) exit 0
echo "[$APPNAME][$(date)] Service exited, restarting in 5 seconds"
sleep 5s
