#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/php-fpm"

echo "[$APPNAME][$(date)] Started as an s6 service"

# create run directory. This is where the locations.conf file will be located.

php-fpm7.4 -g /run/php-fpm.pid -F -O
echo "[$APPNAME][$(date)] Up and running"
while [[ -f /run/php-fpm.pid ]]
do
  sleep 1
done
echo "[$APPNAME][$(date)] Service exited, restarting in 5 seconds"
sleep 5s
