#!/usr/bin/with-contenv bash
#shellcheck shell=bash

APPNAME="$(hostname)/cleanup"

[[ "$CLEANUPINTERVAL" == "" ]] && CLEANUPINTERVAL="3600"

echo "[$APPNAME][$(date)] Cleanup every $((CLEANUPINTERVAL/60)) minutes - next run at $(date -d "@$(( $(date +%s) + CLEANUPINTERVAL ))")."
sleep "${CLEANUPINTERVAL}m"
find /run/notifier/procs -type f -mmin +"$((CLEANUPINTERVAL/60))" -delete >/dev/null 2>&1
